name: update-config-gist
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: update-egg-config-gist
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '>=3.13'
      - name: Install uv
        id: install-uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.24"
          enable-cache: true
          cache-suffix: config-gist
      - name: Install dependencies
        run: |
          uv sync
      - name: Update Gist
        run: |
          ./update-config.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_UPDATER_TOKEN }}
          GIST_ID: ${{ secrets.EGG_CONFIG_GIST_ID }}
          EI_USERID: ${{ secrets.EI_USERID }}
